--CRIAR O BANCO DE DADOS Aula09
CREATE DATABASE ProjAcoes
GO


--HABILITAR O CONTEXTO DO BANCO DE DADOS
USE ProjAcoes
GO

--EXIBE O NOME DO BANCO DE DADOS QUE EXISTE NO SERVIDOR
SELECT name
FROM sys.databases
GO

--CRIA A TABELA USUARIO
CREATE TABLE USUARIO(
	ID_Usuario		INT PRIMARY KEY,
	Nome			VARCHAR(45),
	Endereco		VARCHAR(45),
	Numero			INT,
	Bairro			VARCHAR(35),
	Cidade			VARCHAR(35),
	Cep				INT,
	Cpf				INT,
	Email			VARCHAR(25),
	Sexo			VARCHAR(1),
	Celular			INT,
	Telefone		INT,
)
GO


SELECT *
FROM USUARIO
GO