--EXIBE O NOME DO BANCO DE DADOS QUE EXISTE NO SERVIDOR
SELECT name
FROM sys.databases
GO

USE ProjAcoes
GO

SELECT * FROM PAPEL
GO

DROP TABLE PAPEL

CREATE TABLE PAPEL (
    ID          INT IDENTITY(1,1) PRIMARY KEY,
    Acao        VARCHAR(10),
    Quantidade  INT,
    Valor       FLOAT, 
	Total		FLOAT, 
    Data_Compra datetime DEFAULT GETDATE()
)
GO

--INSERE DADOS NA TABELA PAPEL
INSERT INTO PAPEL(
	ID,
	Acao,
	Quantidade,
	Valor)
VALUES (1,'TAEE11', 75, 35.22)
GO

--INSERE DOIS NOVOS REGISTROS - SINTAXE 1
INSERT INTO PAPEL VALUES (2, 'BBAS3', 15, 35)
INSERT INTO PAPEL VALUES (3, 'VALE3', 100, 45)
GO
 

--Para criar a coluna depois de ja ter a tabela
--ALTER TABLE PAPEL
	--ADD Data_Compra datetime DEFAULT GETDATE()
--GO

--ALTER TABLE PAPEL
--ALTER COLUMN Valor DECIMAL(10, 2);

ALTER TABLE PAPEL
ALTER COLUMN Valor FLOAT;



