
--EXIBE O NOME DO BANCO DE DADOS QUE EXISTE NO SERVIDOR
SELECT name
FROM sys.databases
GO

CREATE DATABASE ProjAcoes;

USE ProjAcoes
GO


CREATE TABLE DIVIDENDOS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    DivAcao NVARCHAR(100),
    ValorDiv DECIMAL(10, 2),
    DataCom DATE,
    DataPag DATE,
    QTD INT,
	TotalDiv DECIMAL(10, 2)
	)
GO

SELECT * FROM DIVIDENDOS
GO

UPDATE DIVIDENDOS
SET TotalDiv = ValorDiv * QTD;
