--EXIBE O NOME DO BANCO DE DADOS QUE EXISTE NO SERVIDOR
SELECT name
FROM sys.databases
GO

USE ProjAcoes
GO

DROP TABLE LOGIN

--CRIA A TABELA login	
CREATE TABLE LOGIN(
	ID			INT IDENTITY(1,1) PRIMARY KEY,
	UsuarioID	INT FOREIGN KEY REFERENCES USUARIO(ID),
	Usuario		VARCHAR(16),
	Senha		VARCHAR(64),
	Foto		VARCHAR(MAX)
)
GO


SELECT * FROM LOGIN
GO

ALTER TABLE LOGIN
ALTER COLUMN Senha VARCHAR(256)

ALTER TABLE LOGIN
ALTER COLUMN Foto VARCHAR(MAX);

