--EXIBE O NOME DO BANCO DE DADOS QUE EXISTE NO SERVIDOR
SELECT name
FROM sys.databases
GO

USE ProjAcoes
GO

--CRIA A TABELA PAPEL
CREATE TABLE PAPEL(
	ID			INT PRIMARY KEY,
	Acao		VARCHAR(6),
	Quantidade	INT,
	Valor		INT,
	)
GO

--INSERE DADOS NA TABELA PAPEL
INSERT INTO PAPEL(
	ID,
	Acao,
	Quantidade,
	Valor)
VALUES (1,'TAEE11', 75, 35.22)
GO

--INSERE DOIS NOVOS REGISTROS - SINTAXE 1
INSERT INTO PAPEL VALUES (2, 'BBAS3', 15, 35)
INSERT INTO PAPEL VALUES (3, 'VALE3', 100, 45)
 
--EXIBE TODOS OS DADOS DA TABELA FUNCIONARIOS
SELECT * FROM PAPEL
GO

