--EXIBE O NOME DO BANCO DE DADOS QUE EXISTE NO SERVIDOR
SELECT name
FROM sys.databases
GO

-- REMOVENDO A TABELA FUNCIONARIOS_2
--DROP TABLE FUNCIONARIOS
--GO

--CRIA A TABELA FUNCIONARIOS
CREATE TABLE PAPEL(
	ACAO		VARCHAR(6) PRIMARY KEY,
	Quantidade	INT,
	Valor		DECIMAL (10,2),
	)
GO

--INSERE DADOS NA TABELA PAPEL
INSERT INTO PAPEL(
	ACAO,
	Quantidade,
	Valor)
VALUES ('PETR4', 10, 25)
GO

--INSERE DOIS NOVOS REGISTROS - SINTAXE 1
INSERT INTO PAPEL VALUES ('BBAS3', 15, 35)
INSERT INTO PAPEL VALUES ('VALE3', 100, 45)

--EXIBE TODOS OS DADOS DA TABELA FUNCIONARIOS
SELECT * FROM PAPEL
GO


