--EXIBE O NOME DO BANCO DE DADOS QUE EXISTE NO SERVIDOR
SELECT name
FROM sys.databases
GO


--CRIA A TABELA USUARIO
CREATE TABLE USUARIO(
	ID			INT PRIMARY KEY,
	Nome		VARCHAR(50),
	Endereco	VARCHAR(50),
	Numero		INT,
	Bairro		VARCHAR(40),
	Cidade		VARCHAR (40),
	CEP			INT,
	CPF			INT,
	Email		VARCHAR (20),
	Sexo		VARCHAR(1),
	Celular		INT,
	Telefone	INT
	)
GO

SELECT * FROM USUARIO
GO


/*--INSERE DADOS NA TABELA PAPEL
INSERT INTO PAPEL(
	ID,
	Acao,
	Quantidade,
	Valor)
VALUES (1,'TAEE11', 75, 35.22)
GO

--INSERE DOIS NOVOS REGISTROS - SINTAXE 1
INSERT INTO PAPEL VALUES (2, 'BBAS3', 15, 35)
INSERT INTO PAPEL VALUES (3, 'VALE3', 100, 45)

--EXIBE TODOS OS DADOS DA TABELA FUNCIONARIOS
SELECT * FROM PAPEL
GO
*/
