--EXIBE O NOME DO BANCO DE DADOS QUE EXISTE NO SERVIDOR
SELECT name
FROM sys.databases
GO


--CRIA A TABELA USUARIO
CREATE TABLE USUARIO(
	ID			INT IDENTITY(1,1) PRIMARY KEY,
	Nome		VARCHAR(50),
	Endereco	VARCHAR(50),
	Numero		INT,
	Bairro		VARCHAR(40),
	Cidade		VARCHAR (40),
	CEP			INT,
	CPF			INT,
	Email		VARCHAR (20),
	Sexo		VARCHAR(1),
	Celular		INT,
	Telefone	INT
	)
GO

SELECT * FROM USUARIO
GO

DROP TABLE USUARIO