--EXIBE O NOME DO BANCO DE DADOS QUE EXISTE NO SERVIDOR
SELECT name
FROM sys.databases
GO

CREATE DATABASE ProjAcoes;

USE ProjAcoes
GO

CREATE TABLE USUARIO(
	ID		INT IDENTITY(1,1) PRIMARY KEY,
	Nome		VARCHAR(50),
	Endereco	VARCHAR(50),
	Numero		VARCHAR(10),
	Bairro		VARCHAR(40),
	Cidade		VARCHAR (40),
	CEP			VARCHAR(8),
	CPF			VARCHAR(11),
	Email		VARCHAR (50),
	Sexo		VARCHAR(1),
	Celular		VARCHAR(15),
	Telefone	VARCHAR(15),
	CONSTRAINT AK_CPF UNIQUE(CPF)
	)
GO

SELECT * FROM USUARIO
GO

CREATE TABLE LOGIN(
	ID			INT IDENTITY(1,1) PRIMARY KEY,
	UsuarioID	INT FOREIGN KEY REFERENCES USUARIO(ID),
	Usuario		VARCHAR(16),
	Senha		VARCHAR(64),
	TipoUsuario	VARCHAR(16),
	Foto		VARCHAR(MAX)
)
GO

SELECT * FROM LOGIN
GO

INSERT INTO USUARIO (Nome)
VALUES ('administrador');

SELECT * FROM USUARIO
GO

SELECT ID FROM USUARIO WHERE Nome = 'administrador';

INSERT INTO LOGIN (UsuarioID, Usuario, Senha, TipoUsuario)
VALUES (1, 'admin', CONVERT(NVARCHAR(64), HASHBYTES('SHA2_256', 'admin'), 2), 'admin');

SELECT * FROM LOGIN
GO
